import type { Metadata } from "next";
import "./globals.css";
import { cn } from "@/utils/cn";
import { Toaster } from "@/components/ui/toaster";
import Header from "@/components/header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn(
          // inter.className,
          "dark text-foreground bg-background"
          // poppins.className
        )}
      >
        {children}
        <Toaster />
      </body>
    </html>
  );
}
