import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Providers } from "./providers";
import { cn } from "@/utils/cn";
// import { Poppins } from "next/font/google";
import { GoogleAnalytics, GoogleTagManager } from "@next/third-parties/google";
import { Partytown } from "@builder.io/partytown/react";

// const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// const poppins = Poppins({
//   subsets: ["latin"],
//   variable: "--font-sans",
//   weight: ["300", "400", "500", "600"],
// });

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn(
          // inter.className,
          "light text-foreground bg-background",
          // poppins.className
        )}
      >
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
